### ISSUE TITLE
On the latest Joomla 4 the plugin causes an error to be displayed:

### ISSUE THREAD

**Issue by webgobe** [zero-24/plg_system_advancedredirect#1]
![image](https://user-images.githubusercontent.com/13080862/149926911-bb8543b1-534d-44c2-842a-14b6b2e279e3.png)

**Comment by zero-24** [comment]
Will take a look this afternoon got another similiar report via Glip today.

Did it happen only after the update or at a fresh new install? And what did you do to get this error?

**Comment by zero-24** [comment]
Looks like the plugin was not ready yet for J4 i have just released an update that would run on J4 and J3: https://github.com/zero-24/plg_system_advancedredirect/releases/tag/1.0.5

Will close here for now let me know when you still get issues.

**Comment by webgobe** [comment]
Thank you, seems to install and run smoothly
