### ISSUE TITLE
Feature request : multiple redirection options

### ISSUE THREAD

**Issue by AlainRnet** [zero-24/plg_system_advancedredirect#2]
Could we image several possible redirection options?
Currently, it is possible to choose between 3 options.
In my case, I have some URLs that start with a certain value and that I would like to redirect to a static URL, while all the others, I would like to be able to redirect them to the expected URL.

In the same way that it is possible to exclude several different URLs, can we imagine creating redirects according to different criteria?

**Comment by zero-24** [comment]
Hi,

I'm sorry to say but this is not on the feature list for now as you aleady noticed and its not something planed in the shorttime. I agree and do see why it would be an interesting feature but do to my limited ressources in the next months its not likely that I will be able to implement such a feature in the comming months. But I will keep this open as an issue / feature request for future releases.

Thanks

**Comment by AlainRnet** [comment]
As written by email this morning, my knowledge is not enough to develop a plugin but still allowed me to update a plugin from J!3 to J!4 (whose changes were really minor). It remains that this plugin has 1 bug: we can install but not edit it because the params are not complete `{"header":"HTTP\/1.1 301 Moved Permanently"}` instead of `{"link_to_link":[{"text":"","link":""}],"header":"HTTP\/1.1 301 Moved Permanently"}`
You may be interested in taking it back. It allows to define redirects (even if there is no 404). It’s always 1 link for 1 link, but it’s very convenient in some cases.
Original: https://xdan.ru/component/ars/?view=release&id=20
Mine: https://github.com/AlainRnet/Redirector/

**Comment by zero-24** [comment]
Hi,
I'm sorry it looks like there is a confusion. This here "plg_system_advancedredirect" is not even close to what you have linked to me above. My plugin works different and is also designed for another usecase. Within my plugin you would still use the joomla core com_redirect which will also take care of the correct redirect code. You plugin seams to be a totally different one which does not seam to be derivated from mine that is held here.

I have also not recived recently any eMail from you regarding this plugin other than the Github Notification from this ticket :)

As for that and the reasons statet above I will close this issue for now as not planed.

**Comment by AlainRnet** [comment]
Sorry for the mix. The email this morning was for something else, the only reference was my inaptitude in coding ;-)
You’re right, the redirector plugin doesn’t do the same thing, but it does redirect. So I thought you might be interested.
That being said, I have taken note of your failure to make a statement on this issue.

**Comment by zero-24** [comment]
Thanks for the clarification, so that i have not just missed your eMail :)

> That being said, I have taken note of your failure to make a statement on this issue.

I'm not sure what you mean by that? I'm missing something here? As of now there are still no plans to implement the feature request you opend in 2023 nor to take over that plugin you mentiond above as it solves a different problem.

I hope this answers your questions?

**Comment by AlainRnet** [comment]
Sorry for bad translation: I understand you close this issue, it's OK.
I hope you'll answer my email, sent yesterday morning to info....to...zu...de
Best regards.

**Comment by zero-24** [comment]
No problem thanks for the clarification.

> I hope you'll answer my email, sent yesterday morning to info....to...zu...de

I would be happy to but i have not got any email to my info@ maybe you could try the mail@. As alternativ you can also reach out to me via Mattermost.

**Comment by AlainRnet** [comment]
You're right, I sent it to mail@
I resend it now.
