### ISSUE TITLE
404 Hits Counter

### ISSUE THREAD

**Issue by creatiweit** [zero-24/plg_system_advancedredirect#3]
Hi,
the plugin work fine, but doesn't register the hits counter.
It's possible to add this feature?
Regards
Emaneuele

**Comment by zero-24** [comment]
what are you looking for in the terms of 404 counter? Can you explain that a bit more in detail?

**Comment by creatiweit** [comment]
Hi Tobias,
Thank you for your reply :)

I'm referring about *404 Hits* value that doesn't increase with
*AdvancedRedirect
*plugin

[image: image.png]

Regards
*Emanuele*

[image: emanuele flain]

[image: creatiwe]



*Emanuele A. FlainSoluzioni per il Web **#Joomla! #Wordpress*

Mobile: +39.328.4242.528
Skype: lelef14
Linkedin: Emanuele-Flain <https://www.linkedin.com/in/emanuele-flain/>
Website: www.creatiwe.it
Mail: ***@***.***
PEC: ***@***.***

Membro del consiglio direttivo dell'Associazione
*Joomla!**Lombardia *www.joomlalombardia.org

**Comment by zero-24** [comment]
Ah ok will take a look later why that is the case.

When i understand you correct the expection would be to incrase the hits counter even when the redirect happend so no actual 404 was triggered. Or better the 404 was triggered but catched and not showed to the users.

Will also check whether that is something that is happening within the core plugin so we keep feature parity.

**Comment by creatiweit** [comment]
Yes the core plugin increase the counter every time the redirect is used :)

Regards
*Emanuele*

[image: emanuele flain]

[image: creatiwe]



*Emanuele A. FlainSoluzioni per il Web **#Joomla! #Wordpress*

Mobile: +39.328.4242.528
Skype: lelef14
Linkedin: Emanuele-Flain <https://www.linkedin.com/in/emanuele-flain/>
Website: www.creatiwe.it
Mail: ***@***.***
PEC: ***@***.***

Membro del consiglio direttivo dell'Associazione
*Joomla!**Lombardia *www.joomlalombardia.org

**Comment by zero-24** [comment]
Hi FYI this has just been fixed: https://github.com/zero-24/plg_system_advancedredirect/commit/1f8dcc4f0908d9639f5f65148f83d3740a8aa67f and a fix has been released as 1.0.6: https://github.com/zero-24/plg_system_advancedredirect/releases/tag/1.0.6

**Comment by creatiweit** [comment]
Great!
Thank you for your support!

Regards
*Emanuele*

[image: emanuele flain]

[image: creatiwe]



*Emanuele A. FlainSoluzioni per il Web **#Joomla! #Wordpress*

Mobile: +39.328.4242.528
Skype: lelef14
Linkedin: Emanuele-Flain <https://www.linkedin.com/in/emanuele-flain/>
Website: www.creatiwe.it
Mail: ***@***.***
PEC: ***@***.***

Membro del consiglio direttivo dell'Associazione
*Joomla!**Lombardia *www.joomlalombardia.org
